// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"

// convert-time.cpp
writable::integers cpp_time_to_seconds(const strings times_in);
extern "C" SEXP _gtfstools_cpp_time_to_seconds(SEXP times_in) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_time_to_seconds(cpp11::as_cpp<cpp11::decay_t<const strings>>(times_in)));
  END_CPP11
}

extern "C" {
/* .Call calls */
extern SEXP _gtfstools_cpp_time_to_seconds(SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_gtfstools_cpp_time_to_seconds", (DL_FUNC) &_gtfstools_cpp_time_to_seconds, 1},
    {NULL, NULL, 0}
};
}

extern "C" void R_init_gtfstools(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
