# Generated by cpp11: do not edit by hand

cpp_time_to_seconds <- function(times_in) {
  .Call(`_gtfstools_cpp_time_to_seconds`, times_in)
}

cpp_seconds_to_string <- function(seconds_from_midnight) {
  .Call(`_gtfstools_cpp_seconds_to_string`, seconds_from_midnight)
}
